export const studyGoals = [
  {
    id: "uk-renting",
    name: "英国租房",
    level: "生活急用",
    description: "看房、押金、合同、维修和入住沟通最常用的表达。",
    words: [
      {
        text: "viewing",
        meaning: "看房",
        phrase: "arrange a viewing",
        example: "Could I arrange a viewing for this flat?",
        definition: "a visit to see a room or property before renting it",
      },
      {
        text: "inventory",
        meaning: "房屋物品清单",
        phrase: "check the inventory",
        example: "I checked the inventory before signing the contract.",
        definition: "a list of items and conditions in a rented place",
      },
      {
        text: "deposit",
        meaning: "押金",
        phrase: "pay a deposit",
        example: "The deposit is protected by a tenancy deposit scheme.",
        definition: "money paid before renting, often returned later",
      },
      {
        text: "tenancy",
        meaning: "租赁；租期",
        phrase: "tenancy agreement",
        example: "The tenancy agreement starts next Monday.",
        definition: "the legal situation or period of renting a place",
      },
      {
        text: "landlord",
        meaning: "房东",
        phrase: "contact the landlord",
        example: "I contacted the landlord about the broken heater.",
        definition: "a person who rents a property to someone else",
      },
      {
        text: "agency",
        meaning: "中介机构",
        phrase: "letting agency",
        example: "The letting agency sent me the contract by email.",
        definition: "a company that helps people rent properties",
      },
      {
        text: "utilities",
        meaning: "水电气等费用",
        phrase: "utilities included",
        example: "Are utilities included in the rent?",
        definition: "services such as gas, electricity, and water",
      },
      {
        text: "council tax",
        meaning: "市政税",
        phrase: "council tax exemption",
        example: "Full-time students can apply for council tax exemption.",
        definition: "a local tax paid for public services in the UK",
      },
      {
        text: "maintenance",
        meaning: "维修维护",
        phrase: "report a maintenance issue",
        example: "I need to report a maintenance issue in the kitchen.",
        definition: "work that keeps a building or item in good condition",
      },
      {
        text: "notice",
        meaning: "通知；提前告知",
        phrase: "give notice",
        example: "I need to give one month's notice before moving out.",
        definition: "a formal warning or message before a change happens",
      },
      {
        text: "furnished",
        meaning: "带家具的",
        phrase: "fully furnished flat",
        example: "Is the flat furnished or unfurnished?",
        definition: "having furniture already provided",
      },
      {
        text: "guarantor",
        meaning: "担保人",
        phrase: "provide a guarantor",
        example: "Some landlords ask international students to provide a guarantor.",
        definition: "a person who promises to pay if you cannot",
      },
    ],
  },
  {
    id: "classroom-speaking",
    name: "课堂发言",
    level: "开口优先",
    description: "提问、没听清、表达观点和小组讨论时能直接用。",
    words: [
      {
        text: "clarify",
        meaning: "澄清；说明",
        phrase: "clarify a point",
        example: "Could you clarify this point for me?",
        definition: "to make an idea easier to understand",
      },
      {
        text: "elaborate",
        meaning: "详细说明",
        phrase: "elaborate on an idea",
        example: "Could you elaborate on that example?",
        definition: "to explain something with more detail",
      },
      {
        text: "perspective",
        meaning: "观点；角度",
        phrase: "from my perspective",
        example: "From my perspective, the argument is convincing.",
        definition: "a way of thinking about something",
      },
      {
        text: "evidence",
        meaning: "证据",
        phrase: "support with evidence",
        example: "Can we support this point with evidence?",
        definition: "facts or information that show something is true",
      },
      {
        text: "counterargument",
        meaning: "反驳观点",
        phrase: "consider a counterargument",
        example: "We should also consider a counterargument.",
        definition: "an argument against another argument",
      },
      {
        text: "contribute",
        meaning: "贡献；参与",
        phrase: "contribute to the discussion",
        example: "I would like to contribute to the discussion.",
        definition: "to give ideas, work, or help",
      },
      {
        text: "summarise",
        meaning: "总结",
        phrase: "summarise the main point",
        example: "Could you summarise the main point again?",
        definition: "to give the main ideas in a short form",
      },
      {
        text: "interrupt",
        meaning: "打断",
        phrase: "sorry to interrupt",
        example: "Sorry to interrupt, but I have a quick question.",
        definition: "to stop someone while they are speaking",
      },
      {
        text: "agree",
        meaning: "同意",
        phrase: "agree with the point",
        example: "I agree with this point because it matches the reading.",
        definition: "to have the same opinion",
      },
      {
        text: "disagree",
        meaning: "不同意",
        phrase: "respectfully disagree",
        example: "I respectfully disagree with that interpretation.",
        definition: "to have a different opinion",
      },
      {
        text: "example",
        meaning: "例子",
        phrase: "give an example",
        example: "Could you give an example of this theory?",
        definition: "something that shows what you mean",
      },
      {
        text: "confusing",
        meaning: "令人困惑的",
        phrase: "find it confusing",
        example: "I find this part confusing. Could you explain it again?",
        definition: "difficult to understand",
      },
    ],
  },
  {
    id: "ielts-writing",
    name: "雅思写作",
    level: "写作高频",
    description: "Task 2 常见论证、原因、结果和让步表达。",
    words: [
      {
        text: "argument",
        meaning: "论点；论证",
        phrase: "main argument",
        example: "The main argument is supported by clear examples.",
        definition: "a reason or set of reasons used to support an idea",
      },
      {
        text: "consequence",
        meaning: "后果",
        phrase: "serious consequence",
        example: "This policy may have serious consequences for students.",
        definition: "a result of an action or situation",
      },
      {
        text: "advantage",
        meaning: "优点",
        phrase: "major advantage",
        example: "One major advantage is that students can study flexibly.",
        definition: "a good or useful feature",
      },
      {
        text: "drawback",
        meaning: "缺点",
        phrase: "possible drawback",
        example: "A possible drawback is the lack of face-to-face support.",
        definition: "a disadvantage or problem",
      },
      {
        text: "sustainable",
        meaning: "可持续的",
        phrase: "sustainable solution",
        example: "Governments should develop sustainable transport systems.",
        definition: "able to continue without causing serious harm",
      },
      {
        text: "inequality",
        meaning: "不平等",
        phrase: "reduce inequality",
        example: "Better education can help reduce inequality.",
        definition: "an unfair difference between groups of people",
      },
      {
        text: "innovation",
        meaning: "创新",
        phrase: "technological innovation",
        example: "Technological innovation can improve healthcare.",
        definition: "a new idea, method, or invention",
      },
      {
        text: "regulation",
        meaning: "监管；规定",
        phrase: "government regulation",
        example: "Government regulation may be necessary to protect consumers.",
        definition: "an official rule or control",
      },
      {
        text: "impact",
        meaning: "影响",
        phrase: "long-term impact",
        example: "The long-term impact of this trend is unclear.",
        definition: "a strong effect on someone or something",
      },
      {
        text: "priority",
        meaning: "优先事项",
        phrase: "top priority",
        example: "Public health should be a top priority.",
        definition: "something that is more important than other things",
      },
      {
        text: "balance",
        meaning: "平衡",
        phrase: "strike a balance",
        example: "Schools need to strike a balance between exams and creativity.",
        definition: "a fair or useful mix of different things",
      },
      {
        text: "solution",
        meaning: "解决方案",
        phrase: "practical solution",
        example: "A practical solution is to improve public transport.",
        definition: "a way to solve a problem",
      },
    ],
  },
];
