export const wordBanks = [
  {
    id: "uk-life",
    name: "英国留学生活",
    level: "先学",
    description: "签证、住宿、银行、看病、超市等刚到英国最常见的词。",
    words: [
      {
        text: "accommodation",
        meaning: "住宿",
        phrase: "student accommodation",
        example: "I am looking for student accommodation near campus.",
        definition: "a place where you live or stay",
      },
      {
        text: "deposit",
        meaning: "押金；存款",
        phrase: "pay a deposit",
        example: "I need to pay a deposit before moving in.",
        definition: "money you pay first to keep or rent something",
      },
      {
        text: "tenancy",
        meaning: "租赁；租期",
        phrase: "tenancy agreement",
        example: "Please read the tenancy agreement carefully.",
        definition: "the period or situation of renting a place",
      },
      {
        text: "landlord",
        meaning: "房东",
        phrase: "contact the landlord",
        example: "I contacted the landlord about the heating.",
        definition: "a person who rents a room or house to you",
      },
      {
        text: "appointment",
        meaning: "预约；约定",
        phrase: "book an appointment",
        example: "I booked an appointment with the GP.",
        definition: "a planned time to meet someone or get a service",
      },
      {
        text: "prescription",
        meaning: "处方",
        phrase: "get a prescription",
        example: "The doctor gave me a prescription.",
        definition: "a doctor's note that lets you get medicine",
      },
      {
        text: "refund",
        meaning: "退款",
        phrase: "ask for a refund",
        example: "Can I ask for a refund?",
        definition: "money that is given back after you return something",
      },
      {
        text: "receipt",
        meaning: "收据；小票",
        phrase: "keep the receipt",
        example: "Keep the receipt in case you need to return it.",
        definition: "a piece of paper or message that proves you paid",
      },
      {
        text: "queue",
        meaning: "队伍；排队",
        phrase: "stand in a queue",
        example: "People were standing in a queue outside the store.",
        definition: "a line of people waiting for something",
      },
      {
        text: "branch",
        meaning: "分行；分店",
        phrase: "bank branch",
        example: "There is a bank branch near my campus.",
        definition: "one local office or shop of a larger company",
      },
    ],
  },
  {
    id: "academic",
    name: "课堂与作业",
    level: "高频",
    description: "听课、交作业、考试和邮件里反复出现的校园词。",
    words: [
      {
        text: "assignment",
        meaning: "作业；任务",
        phrase: "submit an assignment",
        example: "The assignment is due next Friday.",
        definition: "a piece of work you must finish for a course",
      },
      {
        text: "deadline",
        meaning: "截止日期",
        phrase: "meet the deadline",
        example: "I need to meet the deadline for my essay.",
        definition: "the final time or date when work must be finished",
      },
      {
        text: "lecture",
        meaning: "讲座；课程",
        phrase: "attend a lecture",
        example: "I attended a lecture on academic writing.",
        definition: "a class where a teacher talks to a group of students",
      },
      {
        text: "seminar",
        meaning: "研讨课",
        phrase: "join a seminar",
        example: "We discussed the reading in the seminar.",
        definition: "a small class where students discuss a topic",
      },
      {
        text: "tutorial",
        meaning: "辅导课；小课",
        phrase: "weekly tutorial",
        example: "The tutorial helped me understand the topic.",
        definition: "a small class or meeting for help with study",
      },
      {
        text: "feedback",
        meaning: "反馈；意见",
        phrase: "receive feedback",
        example: "I received useful feedback from my tutor.",
        definition: "comments that help you improve your work",
      },
      {
        text: "reference",
        meaning: "参考文献；引用",
        phrase: "add a reference",
        example: "You need to add references to your essay.",
        definition: "information that shows where an idea came from",
      },
      {
        text: "plagiarism",
        meaning: "抄袭",
        phrase: "avoid plagiarism",
        example: "Universities take plagiarism very seriously.",
        definition: "using someone else's work or ideas as your own",
      },
      {
        text: "extension",
        meaning: "延期",
        phrase: "request an extension",
        example: "I requested an extension because I was ill.",
        definition: "extra time to finish something",
      },
      {
        text: "criteria",
        meaning: "标准；准则",
        phrase: "marking criteria",
        example: "Check the marking criteria before writing.",
        definition: "standards used to judge or decide something",
      },
    ],
  },
  {
    id: "speaking",
    name: "开口表达高频词",
    level: "实用",
    description: "让你在问问题、表达不懂、描述困难时更容易开口。",
    words: [
      {
        text: "clarify",
        meaning: "澄清；说明",
        phrase: "clarify a point",
        example: "Could you clarify this point for me?",
        definition: "to make something easier to understand",
      },
      {
        text: "explain",
        meaning: "解释",
        phrase: "explain the reason",
        example: "Could you explain the reason again?",
        definition: "to make an idea clear by giving details",
      },
      {
        text: "repeat",
        meaning: "重复",
        phrase: "repeat the question",
        example: "Could you repeat the question, please?",
        definition: "to say or do something again",
      },
      {
        text: "recommend",
        meaning: "推荐；建议",
        phrase: "recommend a book",
        example: "Can you recommend a good grammar book?",
        definition: "to say that something is good or useful",
      },
      {
        text: "prefer",
        meaning: "更喜欢",
        phrase: "prefer to study alone",
        example: "I prefer to study in the library.",
        definition: "to like one thing more than another thing",
      },
      {
        text: "struggle",
        meaning: "吃力；挣扎",
        phrase: "struggle with listening",
        example: "I struggle with fast English sometimes.",
        definition: "to find something difficult and try hard to do it",
      },
      {
        text: "improve",
        meaning: "提高；改善",
        phrase: "improve my speaking",
        example: "I want to improve my speaking before I go abroad.",
        definition: "to become better or make something better",
      },
      {
        text: "confident",
        meaning: "自信的",
        phrase: "feel confident",
        example: "I feel more confident when I practise every day.",
        definition: "feeling sure that you can do something",
      },
      {
        text: "confusing",
        meaning: "令人困惑的",
        phrase: "a confusing sentence",
        example: "This sentence is confusing to me.",
        definition: "not easy to understand",
      },
      {
        text: "basically",
        meaning: "基本上；简单来说",
        phrase: "basically means",
        example: "It basically means you need to practise more.",
        definition: "used when you explain the main idea simply",
      },
    ],
  },
  {
    id: "ielts-core",
    name: "雅思基础核心",
    level: "备考",
    description: "阅读、听力和写作中常见的基础学术词。",
    words: [
      {
        text: "benefit",
        meaning: "好处；受益",
        phrase: "the main benefit",
        example: "The main benefit is that students become more independent.",
        definition: "a good or useful result",
      },
      {
        text: "challenge",
        meaning: "挑战",
        phrase: "face a challenge",
        example: "Living abroad can be a challenge at first.",
        definition: "something difficult that tests your ability",
      },
      {
        text: "require",
        meaning: "需要；要求",
        phrase: "require attention",
        example: "Academic writing requires careful planning.",
        definition: "to need something or make something necessary",
      },
      {
        text: "develop",
        meaning: "发展；培养",
        phrase: "develop a habit",
        example: "You can develop a habit by studying a little every day.",
        definition: "to grow or make something grow over time",
      },
      {
        text: "increase",
        meaning: "增加",
        phrase: "increase gradually",
        example: "Your vocabulary will increase gradually.",
        definition: "to become bigger in number, amount, or level",
      },
      {
        text: "reduce",
        meaning: "减少",
        phrase: "reduce stress",
        example: "A clear plan can reduce stress.",
        definition: "to make something smaller or less",
      },
      {
        text: "evidence",
        meaning: "证据",
        phrase: "supporting evidence",
        example: "Use evidence to support your opinion.",
        definition: "facts or information that show something is true",
      },
      {
        text: "impact",
        meaning: "影响",
        phrase: "have an impact on",
        example: "Sleep has an impact on learning.",
        definition: "the effect that something has on someone or something",
      },
      {
        text: "significant",
        meaning: "重要的；显著的",
        phrase: "a significant difference",
        example: "Small daily practice can make a significant difference.",
        definition: "important or large enough to notice",
      },
      {
        text: "approach",
        meaning: "方法；处理方式",
        phrase: "a practical approach",
        example: "This is a practical approach to vocabulary learning.",
        definition: "a way of doing or thinking about something",
      },
    ],
  },
  {
    id: "uk-arrival-essentials",
    name: "抵英安顿必备",
    level: "扩展",
    description: "入境、注册、住宿、银行、交通和日常办事里高频出现的词。",
    words: [
      {
        text: "immigration",
        meaning: "入境；移民局",
        phrase: "immigration control",
        example: "I showed my passport at immigration control.",
        definition: "the process of entering another country to live or study",
      },
      {
        text: "enrolment",
        meaning: "注册；入学登记",
        phrase: "complete enrolment",
        example: "I need to complete enrolment before classes start.",
        definition: "the process of officially joining a course or university",
      },
      {
        text: "biometric",
        meaning: "生物识别的",
        phrase: "biometric residence permit",
        example: "I collected my biometric residence permit from the post office.",
        definition: "relating to body information used to identify a person",
      },
      {
        text: "residence",
        meaning: "居住；住所",
        phrase: "proof of residence",
        example: "The bank asked for proof of residence.",
        definition: "the place where someone lives",
      },
      {
        text: "campus",
        meaning: "校园",
        phrase: "main campus",
        example: "My lecture is on the main campus.",
        definition: "the buildings and land of a university or college",
      },
      {
        text: "induction",
        meaning: "新生介绍；入职介绍",
        phrase: "attend induction",
        example: "International students should attend induction week.",
        definition: "an event that introduces new people to a place or system",
      },
      {
        text: "timetable",
        meaning: "课程表；时间表",
        phrase: "check the timetable",
        example: "I checked the timetable before going to class.",
        definition: "a plan showing when classes or events happen",
      },
      {
        text: "module",
        meaning: "课程单元",
        phrase: "choose a module",
        example: "I chose a module in academic writing.",
        definition: "one part of a university course",
      },
      {
        text: "laundry",
        meaning: "洗衣；待洗衣物",
        phrase: "do the laundry",
        example: "I usually do the laundry on Sunday.",
        definition: "clothes that need washing or the activity of washing clothes",
      },
      {
        text: "utility",
        meaning: "水电煤等公共服务",
        phrase: "utility bill",
        example: "A utility bill can be used as proof of address.",
        definition: "a basic service such as electricity, gas, or water",
      },
      {
        text: "electricity",
        meaning: "电",
        phrase: "electricity bill",
        example: "The electricity bill is included in the rent.",
        definition: "power used for lights, heating, and machines",
      },
      {
        text: "heating",
        meaning: "暖气；供暖",
        phrase: "turn on the heating",
        example: "I turned on the heating because the room was cold.",
        definition: "a system that makes a room or building warm",
      },
      {
        text: "maintenance",
        meaning: "维修；维护",
        phrase: "report a maintenance problem",
        example: "I reported a maintenance problem in my room.",
        definition: "work done to keep something in good condition",
      },
      {
        text: "emergency",
        meaning: "紧急情况",
        phrase: "emergency contact",
        example: "Please give us an emergency contact number.",
        definition: "a serious situation that needs immediate action",
      },
      {
        text: "insurance",
        meaning: "保险",
        phrase: "health insurance",
        example: "I checked whether I needed health insurance.",
        definition: "an arrangement that protects you against costs or loss",
      },
      {
        text: "pharmacy",
        meaning: "药房",
        phrase: "go to a pharmacy",
        example: "I went to a pharmacy to buy cold medicine.",
        definition: "a shop or place where medicines are prepared and sold",
      },
      {
        text: "register",
        meaning: "登记；注册",
        phrase: "register with a GP",
        example: "I need to register with a GP near my accommodation.",
        definition: "to put your name on an official list",
      },
      {
        text: "transfer",
        meaning: "转账；转移",
        phrase: "bank transfer",
        example: "I paid the rent by bank transfer.",
        definition: "to move money, information, or someone from one place to another",
      },
      {
        text: "overdraft",
        meaning: "透支",
        phrase: "student overdraft",
        example: "Some student accounts offer an interest-free overdraft.",
        definition: "money you borrow from a bank when your account is below zero",
      },
      {
        text: "contactless",
        meaning: "非接触式的",
        phrase: "contactless payment",
        example: "I used contactless payment on the bus.",
        definition: "using a card or phone to pay without entering a PIN",
      },
      {
        text: "broadband",
        meaning: "宽带",
        phrase: "broadband contract",
        example: "We share the broadband contract in the flat.",
        definition: "a fast internet connection",
      },
      {
        text: "contract",
        meaning: "合同",
        phrase: "sign a contract",
        example: "Read the contract before you sign it.",
        definition: "a legal agreement between people or organisations",
      },
      {
        text: "council",
        meaning: "地方政府；委员会",
        phrase: "local council",
        example: "The local council collects council tax.",
        definition: "a local government organisation",
      },
      {
        text: "exemption",
        meaning: "豁免",
        phrase: "student exemption",
        example: "Full-time students may get a council tax exemption.",
        definition: "permission not to do or pay something",
      },
      {
        text: "queueing",
        meaning: "排队",
        phrase: "queueing system",
        example: "The GP uses an online queueing system.",
        definition: "waiting in a line for your turn",
      },
    ],
  },
  {
    id: "academic-writing-starter",
    name: "学术写作入门",
    level: "写作",
    description: "写 essay、report、作业说明时最容易用到的一组词。",
    words: [
      {
        text: "thesis",
        meaning: "论文观点；毕业论文",
        phrase: "main thesis",
        example: "The main thesis of this essay is clear.",
        definition: "the main idea or argument in a piece of writing",
      },
      {
        text: "argument",
        meaning: "论点；论证",
        phrase: "develop an argument",
        example: "You need to develop your argument with evidence.",
        definition: "a reasoned position supported by facts or examples",
      },
      {
        text: "analyse",
        meaning: "分析",
        phrase: "analyse the data",
        example: "The report analyses the data from the survey.",
        definition: "to examine something carefully to understand it",
      },
      {
        text: "evaluate",
        meaning: "评价；评估",
        phrase: "evaluate the evidence",
        example: "The essay should evaluate the evidence critically.",
        definition: "to judge the value or quality of something",
      },
      {
        text: "compare",
        meaning: "比较",
        phrase: "compare two theories",
        example: "This paragraph compares two theories.",
        definition: "to examine how things are similar or different",
      },
      {
        text: "contrast",
        meaning: "对比",
        phrase: "contrast different views",
        example: "The author contrasts different views on education.",
        definition: "to show how two things are different",
      },
      {
        text: "structure",
        meaning: "结构",
        phrase: "essay structure",
        example: "A clear structure makes your essay easier to read.",
        definition: "the way parts of something are organised",
      },
      {
        text: "outline",
        meaning: "提纲；概述",
        phrase: "write an outline",
        example: "I wrote an outline before starting the essay.",
        definition: "a short plan or summary of the main points",
      },
      {
        text: "draft",
        meaning: "草稿",
        phrase: "first draft",
        example: "My first draft needs more examples.",
        definition: "an early version of a piece of writing",
      },
      {
        text: "paragraph",
        meaning: "段落",
        phrase: "body paragraph",
        example: "Each paragraph should focus on one idea.",
        definition: "a section of writing about one main idea",
      },
      {
        text: "citation",
        meaning: "引用",
        phrase: "in-text citation",
        example: "Remember to add an in-text citation.",
        definition: "a note showing where information came from",
      },
      {
        text: "paraphrase",
        meaning: "改写；释义",
        phrase: "paraphrase a sentence",
        example: "You should paraphrase instead of copying the text.",
        definition: "to express the same idea using different words",
      },
      {
        text: "quotation",
        meaning: "引文",
        phrase: "direct quotation",
        example: "Use a direct quotation only when it is necessary.",
        definition: "words copied exactly from a source",
      },
      {
        text: "source",
        meaning: "来源；资料",
        phrase: "academic source",
        example: "This is not a reliable academic source.",
        definition: "where information comes from",
      },
      {
        text: "bibliography",
        meaning: "参考书目",
        phrase: "add a bibliography",
        example: "The bibliography should be at the end of the essay.",
        definition: "a list of sources used in a piece of work",
      },
      {
        text: "methodology",
        meaning: "方法论；研究方法",
        phrase: "research methodology",
        example: "The methodology explains how the study was done.",
        definition: "the methods used in a study or project",
      },
      {
        text: "finding",
        meaning: "研究发现",
        phrase: "main finding",
        example: "The main finding supports the original argument.",
        definition: "a result discovered through research",
      },
      {
        text: "conclusion",
        meaning: "结论",
        phrase: "draw a conclusion",
        example: "The data allows us to draw a conclusion.",
        definition: "the final judgement or result after considering evidence",
      },
      {
        text: "objective",
        meaning: "目标；客观的",
        phrase: "research objective",
        example: "The research objective is explained in the introduction.",
        definition: "a goal, or something based on facts rather than feelings",
      },
      {
        text: "assumption",
        meaning: "假设",
        phrase: "make an assumption",
        example: "The argument is based on a wrong assumption.",
        definition: "something accepted as true without proof",
      },
      {
        text: "limitation",
        meaning: "限制；局限",
        phrase: "study limitation",
        example: "The small sample size is a limitation of the study.",
        definition: "a weakness or restriction",
      },
      {
        text: "credible",
        meaning: "可信的",
        phrase: "credible source",
        example: "Use credible sources in academic writing.",
        definition: "able to be trusted or believed",
      },
      {
        text: "relevant",
        meaning: "相关的",
        phrase: "relevant example",
        example: "This example is relevant to the topic.",
        definition: "closely connected to the subject",
      },
      {
        text: "coherent",
        meaning: "连贯的",
        phrase: "coherent paragraph",
        example: "Your paragraph is clear and coherent.",
        definition: "logical and easy to understand",
      },
      {
        text: "critical",
        meaning: "批判性的；关键的",
        phrase: "critical thinking",
        example: "University assignments often require critical thinking.",
        definition: "carefully judging the strengths and weaknesses of something",
      },
    ],
  },
  {
    id: "seminar-speaking",
    name: "课堂讨论开口",
    level: "口语",
    description: "seminar、group work、问老师问题时更容易开口的表达词。",
    words: [
      {
        text: "opinion",
        meaning: "观点；看法",
        phrase: "in my opinion",
        example: "In my opinion, the reading is useful.",
        definition: "what someone thinks or believes about something",
      },
      {
        text: "perspective",
        meaning: "视角；观点",
        phrase: "from my perspective",
        example: "From my perspective, the task is quite difficult.",
        definition: "a way of thinking about something",
      },
      {
        text: "agree",
        meaning: "同意",
        phrase: "agree with",
        example: "I agree with your point about time management.",
        definition: "to have the same opinion as someone",
      },
      {
        text: "disagree",
        meaning: "不同意",
        phrase: "disagree with",
        example: "I partly disagree with this argument.",
        definition: "to have a different opinion from someone",
      },
      {
        text: "suggest",
        meaning: "建议；表明",
        phrase: "suggest an idea",
        example: "I suggest we start with the introduction.",
        definition: "to offer an idea or plan",
      },
      {
        text: "mention",
        meaning: "提到",
        phrase: "mention a point",
        example: "The tutor mentioned this point in the lecture.",
        definition: "to say something briefly",
      },
      {
        text: "contribute",
        meaning: "贡献；参与发言",
        phrase: "contribute to the discussion",
        example: "I want to contribute more to the discussion.",
        definition: "to give ideas, help, or effort",
      },
      {
        text: "respond",
        meaning: "回应",
        phrase: "respond to a question",
        example: "I was nervous when I responded to the question.",
        definition: "to answer or react to something",
      },
      {
        text: "summarise",
        meaning: "总结",
        phrase: "summarise the main points",
        example: "Could you summarise the main points?",
        definition: "to give the main ideas in a short form",
      },
      {
        text: "elaborate",
        meaning: "详细说明",
        phrase: "elaborate on",
        example: "Could you elaborate on that idea?",
        definition: "to explain something with more detail",
      },
      {
        text: "example",
        meaning: "例子",
        phrase: "give an example",
        example: "Can you give an example?",
        definition: "something that shows what you mean",
      },
      {
        text: "question",
        meaning: "问题",
        phrase: "ask a question",
        example: "I want to ask a question about the reading.",
        definition: "a sentence used to ask for information",
      },
      {
        text: "confusion",
        meaning: "困惑",
        phrase: "clear up confusion",
        example: "The explanation cleared up my confusion.",
        definition: "a feeling of not understanding something",
      },
      {
        text: "unclear",
        meaning: "不清楚的",
        phrase: "remain unclear",
        example: "This part is still unclear to me.",
        definition: "not easy to understand",
      },
      {
        text: "specific",
        meaning: "具体的",
        phrase: "specific question",
        example: "I have a specific question about the assignment.",
        definition: "clear and exact",
      },
      {
        text: "generally",
        meaning: "通常；一般来说",
        phrase: "generally speaking",
        example: "Generally speaking, students need more practice.",
        definition: "in most cases or without discussing details",
      },
      {
        text: "partly",
        meaning: "部分地",
        phrase: "partly agree",
        example: "I partly agree with this statement.",
        definition: "not completely",
      },
      {
        text: "exactly",
        meaning: "确切地；正是",
        phrase: "not exactly sure",
        example: "I am not exactly sure what this means.",
        definition: "precisely or completely",
      },
      {
        text: "therefore",
        meaning: "因此",
        phrase: "therefore important",
        example: "Practice is therefore important.",
        definition: "for that reason",
      },
      {
        text: "however",
        meaning: "然而",
        phrase: "however difficult",
        example: "However, this method takes time.",
        definition: "used to introduce a contrast",
      },
      {
        text: "moreover",
        meaning: "此外",
        phrase: "moreover, it shows",
        example: "Moreover, it shows that students need support.",
        definition: "used to add another point",
      },
      {
        text: "initially",
        meaning: "最初",
        phrase: "initially difficult",
        example: "The seminar was initially difficult for me.",
        definition: "at the beginning",
      },
      {
        text: "eventually",
        meaning: "最终",
        phrase: "eventually improve",
        example: "My speaking will eventually improve.",
        definition: "in the end, after some time",
      },
      {
        text: "participate",
        meaning: "参加；参与",
        phrase: "participate in class",
        example: "I try to participate in class every week.",
        definition: "to take part in an activity",
      },
      {
        text: "collaborate",
        meaning: "合作",
        phrase: "collaborate with classmates",
        example: "We collaborated on a group presentation.",
        definition: "to work with other people to do something",
      },
    ],
  },
  {
    id: "ielts-topic-words",
    name: "雅思话题扩展",
    level: "话题",
    description: "教育、科技、环境、社会类话题中常见的基础表达。",
    words: [
      {
        text: "education",
        meaning: "教育",
        phrase: "higher education",
        example: "Higher education can improve career opportunities.",
        definition: "the process of teaching and learning",
      },
      {
        text: "technology",
        meaning: "科技；技术",
        phrase: "modern technology",
        example: "Modern technology has changed how people communicate.",
        definition: "tools, machines, and systems based on scientific knowledge",
      },
      {
        text: "environment",
        meaning: "环境",
        phrase: "protect the environment",
        example: "People should take action to protect the environment.",
        definition: "the natural world around us",
      },
      {
        text: "pollution",
        meaning: "污染",
        phrase: "air pollution",
        example: "Air pollution is a serious problem in many cities.",
        definition: "harmful substances in air, water, or land",
      },
      {
        text: "sustainable",
        meaning: "可持续的",
        phrase: "sustainable development",
        example: "Sustainable development is important for the future.",
        definition: "able to continue without damaging the environment",
      },
      {
        text: "urban",
        meaning: "城市的",
        phrase: "urban areas",
        example: "Urban areas often have better public transport.",
        definition: "relating to cities or towns",
      },
      {
        text: "rural",
        meaning: "乡村的",
        phrase: "rural communities",
        example: "Rural communities may have fewer services.",
        definition: "relating to the countryside",
      },
      {
        text: "population",
        meaning: "人口",
        phrase: "growing population",
        example: "A growing population creates pressure on housing.",
        definition: "the number of people living in a place",
      },
      {
        text: "community",
        meaning: "社区；群体",
        phrase: "local community",
        example: "Volunteering helps the local community.",
        definition: "a group of people living in the same area or sharing interests",
      },
      {
        text: "economy",
        meaning: "经济",
        phrase: "local economy",
        example: "Tourism can support the local economy.",
        definition: "the system of money, trade, and industry in a place",
      },
      {
        text: "employment",
        meaning: "就业",
        phrase: "employment opportunities",
        example: "Education can increase employment opportunities.",
        definition: "work that someone is paid to do",
      },
      {
        text: "income",
        meaning: "收入",
        phrase: "low income",
        example: "Low income can affect access to education.",
        definition: "money someone receives from work or other sources",
      },
      {
        text: "inequality",
        meaning: "不平等",
        phrase: "social inequality",
        example: "Social inequality can affect health outcomes.",
        definition: "an unfair difference between groups of people",
      },
      {
        text: "global",
        meaning: "全球的",
        phrase: "global issue",
        example: "Climate change is a global issue.",
        definition: "relating to the whole world",
      },
      {
        text: "local",
        meaning: "当地的",
        phrase: "local problem",
        example: "The council is trying to solve a local problem.",
        definition: "relating to a particular area",
      },
      {
        text: "healthcare",
        meaning: "医疗保健",
        phrase: "healthcare system",
        example: "A good healthcare system improves quality of life.",
        definition: "services that help people stay healthy or treat illness",
      },
      {
        text: "wellbeing",
        meaning: "身心健康；幸福感",
        phrase: "mental wellbeing",
        example: "Sleep has an impact on mental wellbeing.",
        definition: "the state of being healthy and happy",
      },
      {
        text: "pressure",
        meaning: "压力",
        phrase: "academic pressure",
        example: "Academic pressure can affect students.",
        definition: "stress caused by demands or difficult situations",
      },
      {
        text: "responsibility",
        meaning: "责任",
        phrase: "personal responsibility",
        example: "Students have personal responsibility for their learning.",
        definition: "a duty to do or care about something",
      },
      {
        text: "opportunity",
        meaning: "机会",
        phrase: "career opportunity",
        example: "Studying abroad can create new career opportunities.",
        definition: "a chance to do something useful or good",
      },
      {
        text: "innovation",
        meaning: "创新",
        phrase: "technological innovation",
        example: "Technological innovation can improve productivity.",
        definition: "a new idea, method, or invention",
      },
      {
        text: "traditional",
        meaning: "传统的",
        phrase: "traditional values",
        example: "Some people prefer traditional ways of learning.",
        definition: "relating to customs or methods from the past",
      },
      {
        text: "individual",
        meaning: "个人；个人的",
        phrase: "individual choice",
        example: "Online learning gives students more individual choice.",
        definition: "one person, considered separately from a group",
      },
      {
        text: "society",
        meaning: "社会",
        phrase: "modern society",
        example: "Modern society depends heavily on technology.",
        definition: "people living together in an organised community",
      },
      {
        text: "beneficial",
        meaning: "有益的",
        phrase: "beneficial effect",
        example: "Regular exercise has a beneficial effect on health.",
        definition: "having a good or useful result",
      },
    ],
  },
];
